/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleView: typeof import('./src/components/views/ArticleView.vue')['default']
    CustomTabBar: typeof import('./src/components/CustomTabBar.vue')['default']
    FullPlayer: typeof import('./src/components/FullPlayer.vue')['default']
    HomeView: typeof import('./src/components/views/HomeView.vue')['default']
    MediaView: typeof import('./src/components/views/MediaView.vue')['default']
    MiniPlayer: typeof import('./src/components/MiniPlayer.vue')['default']
    MusicView: typeof import('./src/components/views/MusicView.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdFab: typeof import('wot-design-uni/components/wd-fab/wd-fab.vue')['default']
    WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['default']
    WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['default']
    WdToast: typeof import('wot-design-uni/components/wd-toast/wd-toast.vue')['default']
  }
}
