/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleView: typeof import('./src/components/views/ArticleView.vue')['default']
    CustomTabBar: typeof import('./src/components/CustomTabBar.vue')['default']
    FullPlayer: typeof import('./src/components/FullPlayer.vue')['default']
    HomeView: typeof import('./src/components/views/HomeView.vue')['default']
    LibraryView: typeof import('./src/components/views/LibraryView.vue')['default']
    MediaView: typeof import('./src/components/views/MediaView.vue')['default']
    MiniPlayer: typeof import('./src/components/MiniPlayer.vue')['default']
    MusicView: typeof import('./src/components/views/MusicView.vue')['default']
    ProfileView: typeof import('./src/components/views/ProfileView.vue')['default']
    UpdatePopup: typeof import('./src/components/UpdatePopup.vue')['default']
  }
}
